### ISSUE TITLE
Page Title

### ISSUE THREAD

**Issue by Nebir** [technext/wow#2]
Give a title between head tag for every html page
Resource: [http://www.w3schools.com/tags/tag_title.asp]
**Demo:**
`<title>WOW - Home</title>` - for index.html
`<title>WOW - Generic</title>` - for generic.html
`<title>WOW - Element</title>` - for element.html

**Comment by ahnayem-cse-sust** [comment]
complete

**Comment by Nebir** [comment]
:+1:
