### ISSUE TITLE
Home page - header

### ISSUE THREAD

**Issue by Nebir** [technext/wow#3]
Please try to combine following classes in a div called header 
- .wow-logo,
- .lora
- .wow-btn
- next div containing the image

**Demo:**
`<section class="header">
  <div class="wow-logo">
    ....
  </div>
  <div class="lora">
    ....
  </div>
  <div class="wow-btn">
    ....
  </div>
  <div>
    <center><img src="assets/img/1.jpg"  width="600" class="img-responsive"></center>
 </div>
</section>`

and make this header height as the full-height of every user device. For this, you can take help from this link [http://markup.themewagon.com/conference_pro/]

**Comment by ahnayem-cse-sust** [comment]
solved

**Comment by Nebir** [comment]
good job
